:function-body: examples/function_body.json

=== Function body formatting

In this example, we show how to include the source code from a Sail function.

==== Sail source

[source,sail]
----
include::function_body.sail[]
----

==== Result

include::sailcomment:main[from=function-body]

For example, to format the entire function:

[source,adoc]
----
sail::main[from=function-body]
----

sail::main[from=function-body]

If we want to reference an included function, we can use an Asciidoc
cross-reference. The sail macro will generate an id using the name of
the Sail function and the `from` attribute. In this example, we can
use `pass:[&lt;&lt;function-body-main&gt;&gt;]` to reference the
function which results in <<function-body-main>>. In can also be given
a name in the standard Asciidoc way using
`pass:[&lt;&lt;function-body-main,main&gt;&gt;]`, which results in
<<function-body-main,main>>.

We can format just the body of the function using `part=body`:

[source,adoc]
----
sail::main[from=function-body,part=body]
----

sail::main[from=function-body,part=body]

The body can be unindented the block using either `unindent` or `dedent`:

[source,adoc]
----
sail::main[from=function-body,part=body,dedent]
----

sail::main[from=function-body,part=body,dedent]

We can also trim leading and trailing whitespace using `trim` or `strip` (although this is not useful here):

[source,adoc]
----
sail::main[from=function-body,part=body,trim]
----

sail::main[from=function-body,part=body,trim]

Rather than using the `sail` block macro directly we can also use an include macro, like so:

[source,adoc]
-----
[source,sail]
----
\include::sail:main[from=function-body]
----
-----

[source,sail]
----
include::sail:main[from=function-body]
----

The advantage of using the include macro is it lets us include
multiple definitions within the same asciidoc source block, at the
expense of being more verbose. It can also be used in places where the
asciidoc processor doesn't like seeing a block macro, but would allow
a block.

A disadvantage of using the include block is that it doesn't
automatically generate an anchor for us to cross reference. An anchor
would instead have to be manually added to the block.
