ifndef::backend-pdf[]
:sail-xref:
endif::[]

:sail-xref-external: https://github.com/Alasdair/asciidoctor-sail/blob/%commit%/doc/%file%#L%line%

:xref-example: examples/xref.json

=== Automatic cross-referencing

==== Sail source

[source,sail]
----
include::xref.sail[]
----

==== Example

The asciidoctor-sail plugin supports automatic cross referencing
between Sail source included in a document when using the asciidoctor
html5 backend. Note that this automatic crossreferencing does not work
when using asciidoctor-pdf. To enable this, use the `:sail-xref:`
attribute:

[source,adoc]
----
:sail-xref:
----

We can then include a definition or type signature in our source:

sail::foo[type=val,from=xref-example]

Then any Sail definition that references it will contain a link:

sail::bar[from=xref-example]

The Sail definitions can appear in any order in the AsciiDoc source.
For example, the above example also contained a link to the `baz`
function, which is below:

sail::baz[from=xref-example]

The `quux` function is not included in this document, so a link can be
inserted to an external repository. This is controlled by the
`:sail-xref-external:` document attribute, which if present provides a
template for any such external links:

[source,adoc]
----
:sail-xref-external: https://github.com/asciidoctor-sail/blob/%commit%/doc/%file%#L%line%
----

Cross referencing can be disabled by negating the `:sail-xref:`
attribute in the standard AsciiDoc way:

[source,adoc]
----
:sail-xref!:
----

ifndef::backend-pdf[]
:sail-xref!:
endif::[]

And subsequent inclusions will not contain links:

sail::bar[from=xref-example]
