= Examples

== Build

This directory contains various examples showing how the plugin can be used.

Each example includes a `example.sail` file, and a corresponding
`example.adoc` file. For each such pair:

[source,sh]
----
make example.pdf
----

will build a corresponding PDF using asciidoctor-pdf.

There are pre-built versions of each of the examples in the `built` subdirectory.

== Example list

* `function_body` -- Shows how to document a simple function, with various options for formatting the function body.

* `clauses` -- Shows how to document a Sail definition with multiple clauses, such as the `execute` function in the Sail RISC-V model.

* `mapping_clauses` -- Shows how to document the clauses of bi-directional mappings in Sail, such as the `encdec` function in the Sail RISC-V model.

* `anchor` -- Shows how to include free-standing documentation comments in the Sail source into processed documentation using _anchors_.

* `wavedrom` -- Shows how to produce WaveDrom encoding diagrams using https://docs.asciidoctor.org/diagram-extension/latest/[asciidoctor-diagram] and https://wavedrom.com/[WaveDrom].
